# Path to your oh-my-zsh installation.
export ZSH=/home/rasmus/.oh-my-zsh

# Set name of the theme to load.
ZSH_THEME="crunch"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to enable command auto-correction.
ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

DISABLE_UNTRACKED_FILES_DIRTY="true"

plugins=(gitfast compleat common-aliases web-search systemd django z catimg custom-aliases)


# User configuration
export PATH="/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl"

source $ZSH/oh-my-zsh.sh
export LANG=en_US.UTF-8

# Compilation flags
export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

## Startup
[[ -z $DISPLAY && $XDG_VTNR -eq 1 ]] && exec startx
source /usr/bin/virtualenvwrapper.sh
